[package]
authors = ["Sam Hill <sam.j.hill@protonmail.com>"]
name = "micro_sensor"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
embassy-executor = { version = "0.6.0", features = ["arch-cortex-m", "executor-thread", "integrated-timers"] }
embassy-nrf = { version = "0.2.0", features = ["nrf52833", "time-driver-rtc1", "gpiote"] }
embassy-sync = "0.6.0"
embassy-time = "0.3.2"
panic-rtt-target = "0.1.3"
